### ISSUE TITLE
Image acquisition using tango events

### ISSUE THREAD

**Issue by izadworny** [esrf-bliss/Lima#57]
Hi,
I use GUI for Lima based on Taurus, which uses LiveViewer DS for image acquisition. Unfortunately this DS is  no longer maintain and don't use tango event (Taurus starts polling). I have problem with image acquisition because events with images comes in bunches and image is jerky.
How can I use tango event for image acquisition? I have found last_image and video_last_image but they are invalid.

![obraz](https://user-images.githubusercontent.com/25221609/29858542-2be89ed2-8d5e-11e7-9202-761e137962ba.png)
 
regards 
IZ

**Comment by sebastien-petitdemange** [comment]
Hi,

How did you get that events comes in bunch? Did you trace the network
packets? Are you sure that the Taurus gui can handle the framerate?

last_image and video_last_image are not invalid, those two attributes
are exported as DevEncoded.

SEB

**Comment by izadworny** [comment]
We used debug informations about events from out widgets  and we could see on console how events arrived.
I tried to reduce bandwidth and I set image_bin=[2,2]. I'm going to eliminate unnecessary elements such LiveViewer DS. The question still remains - How can I acquire image directly from LimaCCDs. We need 25fps.

**Comment by sebastien-petitdemange** [comment]
Hi IZ,

I've probably misunderstood what is exactly your problem. I need to
clarify some points.

So you were used to display images in your GUI by reading the JpegImage
attribute in LiveViewer.
And now you want to use the "last_image" event.
But you notice that this event comes in a bunch of image.
That why the image you display is jerky.
Is that correct?


On 08/30/2017 12:21 PM, izadworny wrote:
> We used debug informations about events from out widgets  and we could see on console how events arrived.
Is it in the same GUI which displays images?
Are you really sure that your GUI can keep-up with such frame rate?

> I tried to reduce bandwidth and I set image_bin=[2,2].
> I'm going to eliminate unnecessary elements such LiveViewer DS. The question still remains - How can I acquire image directly from LimaCCDs. We need 25fps.
> 

You've to set the properties:
  - DefaultMaxEventRate to 25 (at least)
  - TangoEvent to true
Then during an acqusition, the event "last_image" will be fire each time
there is a new image with 25 frames per second maximum.

Then in your GUI just have to register on this event and decode/display
the image.


SEB

**Comment by daneos** [comment]
I tried to subscribe to `last_image`, but for every event type I'm getting only the first event and nothing more. It doesn't depend on if the acquisition was started when subscribing or not, also Tango event configuration seems to have no effect.
It seems like the events are not fired at all.
This is when using Tango to subscribe. When using Taurus (just a subclass of `TaurusWidget`, for which I `setModel()`) I get more events, but the number of events is nowhere near the number of acquired frames (I'd expect that an event is fired for each frame).
Additionally, once every two events I get this message:
`BL-04BM/DIA/BL-04BM-DIA-CCAM3.video_last_image_counter: Activating polling. Reason: API_EventTimeout`
which is really strange, since I subscribe only to `last_image` and not `video_last_image_counter`. The application I use for testing is really a minimal one, so I don't think it subscribes to something behind the scenes.
