### ISSUE TITLE
doc changes without version incrementation

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#74]
Hi,
I noticed that the documentation has evolved without upgrading its version.
I saw this by comparing the current PDF version (1.7.2 of 199 pages) I got on readthedocs and the one I downloaded in november, 28th (1.7.2 of 231 pages).

Perhaps something broke into the version update?

**Comment by PhilLAL** [comment]
Perhaps I created this issue in wrong repo, it probably should be moved to https://github.com/esrf-bliss/Lima-documentation/issues, isn't it?
Please accept my apologies, I can create another one if you can't move it.
Regards.

**Comment by sdebionne** [comment]
Hi Phil, it's fine to report the doc issues here. Actually the doc has been reintegrated in the main repo and Lima-documentation should be locked. Regarding the version, we have not tagged 1.8.0 yet since there a couple of thing that we need to fix/improve. But once we do, the version should be automatically updated.

**Comment by PhilLAL** [comment]
Thank you.
FYI, I opened after this topic an issue in this doc subrepo here: https://github.com/esrf-bliss/Lima-documentation/issues/11 which can help increase the doc I hope.
